### ISSUE TITLE
Content: Quiz 01.01. negation in answers

### ISSUE THREAD

**Issue by SophiaFedder98** [prolog-hhu/website#22]
You can only write positive answers. E.g. "Molly ist feminin", but you can't say: "Molly ist nicht maskulin" or "Molly ist kein Elternteil von Harry", which is context wise true, but would be marked as a false answer. 
Solution: Either we add to the possible answers Regexes for negation or we state in the description of the task clearly that negation in the answers is excluded.

**Comment by smnmnkr** [comment]
Thanks! That seems like a good throw-in.  We should agree uniformly for all the following tasks on how we want to handle such questions. Both options require manual content maintenance.
