### ISSUE TITLE
Content: Consistent naming/numbering of 'Aufgaben' & 'Quizzes'

### ISSUE THREAD

**Issue by jegny100** [prolog-hhu/website#25]
We should agree on a common naming scheme before the content is transferred from the original LMS to the current one.

Were there any problems or suggestions for improvement with last year's structure?

**My suggestion**
With the tasks: 

> chapter number. Task number. Task name

At the quizzes:

> chapter number.task.number.task.name. Quiz number. task name - quiz name

**Example**
Related to the first task, the family database, which contains three quizzes:
- 'Aufgaben'
    - 01.01. Familiendatenbank

- 'Quizzes'
    - 01.01.01 Familiendatenbank – Wissensbasis
    - 01.01.02 Familiendatenbank – Verstehen der Aufgabe
    - 01.01.03 Familiendatenbank – Prolog

**Comment by smnmnkr** [comment]
Accepted iff we can agree on having a dot at the end of each numbered sequence. E. g. 01.01.01. instead of 01.01.01

**Comment by smnmnkr** [comment]
added wiki page: https://github.com/prolog-hhu/website/wiki/structure-and-naming-Guidelines
